global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Threading;
global using System;
global using MediatR;
global using TravelBook.Core.SeedWork;
global using TravelBook.Core.ProjectAggregate;
